### PR TITLE
Initial implementation

### LINKED ISSUE #139: Create and add plugin to expose an endpoint for adding HLS video URLs
PR https://github.com/mitodl/edx-platform/pull/138 adds a UI to add an already-encoded HLS video URL in Studio (before that PR, Studio only allows you to upload and encode a video directly in the app). This approach works, but it creates some extra work for the course author, and more importantly, it adds a lot of code to our fork of edx-platform and increases the drift between our forked repo and the edX repo.

As an alternate approach, we want to create a separate plugin/extension app that exposes a new HTTP API endpoint. That endpoint would take a request to add an HLS video URL and run through all the necessary steps to make that video available in Studio. The first client making requests to that endpoint would be OVS ([`odl-video-service`](https://github.com/mitodl/odl-video-service)).

Acceptance criteria:
- [ ] New repo created for the plugin/extension
- [ ] Plugin/extension repo added as a requirement in this repo
- [ ] Requests to add HLS videos via the new endpoint are working

### PR DESCRIPTION
**Pull request by gsidebo**
#### What are the relevant tickets?

Closes https://github.com/mitodl/edx-platform/issues/139

#### What's this PR do?

When installed in Open edX, this plugin app adds endpoints to LMS for creating a new HLS video for a course and for fetching all existing videos for a course

#### Where should the reviewer start?

Probably `edx_video_api/views.py`

#### How should this be manually tested?

Go through the README!

#### Any background context you want to provide?

This is meant to essentially replace the work done in https://github.com/mitodl/edx-platform/pull/138

### CODE REVIEW

**Comment by ahmed-arbisoft** [comment]
Not able to review this, perhaps because I don't have correct access/permissions on the repo itself. The plugin app itself worked fine, however there were some issues I faced while installing it:

```
edx-video-api/edx_video_api/apps.py
-----------------------------------

3:  from django.conf import settings

6:  EdxConstants = import_string(settings.VIDEO_API_EDX_CONSTANTS)
7:  ProjectType = EdxConstants.ProjectType
8:  SettingsType = EdxConstants.SettingsType
9:  PluginURLs = EdxConstants.PluginURLs
10: PluginSettings = EdxConstants.PluginSettings
```
I'm not sure because I haven't dealt with it in this detail before but I guess the django settings aren't properly evaluated at this moment. Following the `README.md` provided for this repo I faced the following error:

```
ERROR:stevedore.extension:Could not load 'edx_video_api': The SECRET_KEY setting must not be empty.
```

Which led me to look at other plugin apps (I looked at `zendesk_proxy` for the purpose of this review). In their `apps.py` the above values (constants) were being imported directly from `openedx.core.djangoapps.plugins.constants`. I removed the lines `3` and `6-10` from `apps.py` and replaced it with

```
from openedx.core.djangoapps.plugins.constants import ProjectType, SettingsType, PluginURLs, PluginSettings
```

and the plugin started to work properly. On a side note, both the create and list were working fine.

Could you please update this or let me know if I'm doing something the wrong way?

**Comment by gsidebo** [comment]
@ahmed-arbisoft I _think_ I just gave access to you and the rest of the Arbisoft team. Let me know if that worked. I'll look into your comment 👍

**Comment by gsidebo** [comment]
@ahmed-arbisoft Just made a bunch of changes to the package layout, config, and handling of settings. Should install correctly now

**Review by ahmed-arbisoft — APPROVED** [review]
Works fine on my end, installed ok as well :ok_hand:

**Pull request merged**
